#' # Reduced BrainNetTest replication
#'
#' This standalone script exercises the same validated API and simulation
#' pipeline as `code-full.R` with a small, predeclared study. It is designed to
#' run comfortably within the JSS review-time guideline. It does **not**
#' reproduce the exact Monte Carlo values printed in the manuscript; those are
#' generated by `code-full.R`.

options(width = 90, useFancyQuotes = FALSE)
RNGkind("L'Ecuyer-CMRG")
suppressPackageStartupMessages(library("BrainNetTest"))

alpha <- 0.05
n_replications <- 200L
n_permutations <- 199L
master_seed <- 20260713L

output_dir <- "generated-quick"
dir.create(output_dir, showWarnings = FALSE)

#' ## Helpers

draw_group <- function(n_graphs, probability) {
  replicate(
    n_graphs,
    generate_random_graph(6L, probability),
    simplify = FALSE
  )
}

run_cell <- function(probability_a, probability_b, seed_offset) {
  rows <- vector("list", n_replications)

  for (replicate_index in seq_len(n_replications)) {
    seed <- master_seed + seed_offset + replicate_index
    set.seed(seed)
    data <- brainnet_data(list(
      GroupA = draw_group(10L, probability_a),
      GroupB = draw_group(10L, probability_b)
    ))
    result <- brainnet_test(
      data,
      alpha = alpha,
      n_permutations = n_permutations,
      exact = "never",
      adjust = "holm",
      seed = seed + 50000L
    )
    rows[[replicate_index]] <- data.frame(
      replicate = replicate_index,
      global_reject = result$global$p_value <= alpha,
      any_edge_selected = any(result$edges$selected),
      n_selected = sum(result$edges$selected)
    )
  }

  do.call(rbind, rows)
}

#' ## Complete null
#'
#' Both groups use independent Bernoulli edges with probability 0.30.

null_results <- run_cell(0.30, 0.30, seed_offset = 0L)

#' ## Marginal-frequency alternative
#'
#' Group edge probabilities are 0.15 and 0.65.

alternative_results <- run_cell(0.15, 0.65, seed_offset = 100000L)

summary <- data.frame(
  cell = c("complete_null", "frequency_shift"),
  global_rejection = c(
    mean(null_results$global_reject),
    mean(alternative_results$global_reject)
  ),
  any_edge_selected = c(
    mean(null_results$any_edge_selected),
    mean(alternative_results$any_edge_selected)
  ),
  mean_selected = c(
    mean(null_results$n_selected),
    mean(alternative_results$n_selected)
  )
)

print(summary)
write.csv(
  summary,
  file.path(output_dir, "reduced_summary.csv"),
  row.names = FALSE
)

#' ## Reduced validation figure

pdf(file.path(output_dir, "reduced_summary.pdf"), width = 7, height = 4)
barplot(
  rbind(summary$global_rejection, summary$any_edge_selected),
  beside = TRUE,
  names.arg = summary$cell,
  ylim = c(0, 1),
  col = c("steelblue", "firebrick"),
  ylab = "Observed rate",
  legend.text = c("Global rejection", "Any Holm-selected edge"),
  args.legend = list(x = "topleft", bty = "n")
)
abline(h = alpha, lty = 2)
dev.off()

#' ## Session information

sessionInfo()
