# R/identify_critical_links.R
# Fast, mathematically exact implementation.

#' Identify Critical Edges That Explain Population Differences
#'
#' Iteratively identifies the edges that drive the observed difference between
#' two or more populations of brain networks, using the permutation-based
#' L1-distance ANOVA test of Fraiman and Fraiman (2018). Edges are ranked by
#' their marginal p-value, then removed in batches until the global test is no
#' longer significant. The permutation null is re-evaluated incrementally via
#' a prefix-sum decomposition of T, which avoids recomputing the statistic
#' from scratch at every step.
#'
#' @param populations A named \code{list} with at least two elements. Each
#'   element is itself a list of square, binary, symmetric adjacency matrices
#'   (zero diagonal, no self-loops). All graphs must share the same number of
#'   nodes.
#' @param alpha Numeric significance level used both for the global test and
#'   for the iterative edge-removal stopping rule. Default \code{0.05}.
#' @param method Character string selecting the marginal edge test used to
#'   rank candidate edges. One of \code{"fisher"} (default),
#'   \code{"chi.squared"}, or \code{"prop"}. See
#'   \code{\link{compute_edge_pvalues}}.
#' @param adjust_method Character string passed to \code{\link[stats]{p.adjust}}
#'   for multiplicity correction of the marginal p-values. Default
#'   \code{"none"}.
#' @param batch_size Positive integer giving the number of edges to drop per
#'   iteration. Larger values speed up the procedure at the cost of coarser
#'   resolution. Default \code{1}.
#' @param n_permutations Positive integer giving the number of permutation
#'   replicates used to approximate the null distribution of T. Default
#'   \code{1000}.
#' @param a Positive numeric normalisation constant for the test statistic T
#'   (see \code{\link{compute_test_statistic}}). Default \code{1}.
#' @param seed Optional integer seed for reproducibility of the permutation
#'   replicates. Default \code{NULL}.
#'
#' @return An object of class \code{"critical_links"}: a \code{list} with the
#'   components
#'   \describe{
#'     \item{critical_edges}{a \code{data.frame} with columns \code{node1},
#'       \code{node2}, \code{p_value}, listing the edges removed until the test
#'       became non-significant, ordered from most to least significant;
#'       \code{NULL} if the global test was not significant.}
#'     \item{edges_removed}{a list of length-2 integer vectors giving the
#'       \code{(i, j)} indices of the removed edges, in removal order.}
#'     \item{modified_populations}{the input \code{populations} with the
#'       critical edges zeroed out in every graph.}
#'     \item{p_value}{the permutation \eqn{p} value of the global test on the
#'       unmodified data, \code{NA} when there were no candidate edges.}
#'     \item{n_edges}{the number of candidate edges considered.}
#'     \item{settings}{the arguments the analysis ran with.}
#'     \item{call}{the matched call.}
#'   }
#'   Methods are provided for \code{\link[=print.critical_links]{print}},
#'   \code{\link[=summary.critical_links]{summary}} and
#'   \code{\link[=plot.critical_links]{plot}}. The first three components are
#'   unchanged from earlier versions, so code that extracts them keeps working.
#'
#' @details The implementation exploits the fact that T decomposes as a sum of
#'   per-edge contributions \eqn{\Delta_e}. Removing an edge e is equivalent
#'   to subtracting \eqn{\Delta_e} from T, so prefix sums of the sorted
#'   \eqn{\Delta_e} values give the test statistic after any number of
#'   removals in O(1). The permutation null is built once via a single BLAS
#'   matrix multiplication and reused for every iteration, reducing the
#'   overall complexity from O(K * B * |E| * m) (naive) to O(B * |E| * m).
#'
#'   Permutation replicates are generated by uniformly permuting the group
#'   labels across the pooled sample of all graphs, while preserving the
#'   original group sizes (sampling without replacement).
#'
#' @references
#' Fraiman, D. and Fraiman, R. (2018) An ANOVA approach for statistical
#' comparisons of brain networks. \emph{Scientific Reports}, 8, 4746.
#' \doi{10.1038/s41598-018-23152-5}.
#'
#' @seealso \code{\link{print.critical_links}},
#'   \code{\link{summary.critical_links}}, \code{\link{plot.critical_links}},
#'   \code{\link{compute_test_statistic}},
#'   \code{\link{compute_edge_pvalues}}, \code{\link{get_critical_nodes}}.
#'
#' @export
#' @examples
#' \donttest{
#' set.seed(1)
#' control <- generate_category_graphs(
#'   n_graphs = 15, n_nodes = 10, n_communities = 2,
#'   base_intra_prob = 0.8, base_inter_prob = 0.2, seed = 1)
#' patient <- generate_category_graphs(
#'   n_graphs = 15, n_nodes = 10, n_communities = 2,
#'   base_intra_prob = 0.5, base_inter_prob = 0.5, seed = 2)
#' populations <- list(Control = control, Patient = patient)
#' result <- identify_critical_links(
#'   populations, alpha = 0.05, method = "fisher",
#'   n_permutations = 200, seed = 42)
#' result
#' summary(result)
#' head(result$critical_edges)
#' }
identify_critical_links <- function(populations,
                                    alpha          = 0.05,
                                    method         = "fisher",
                                    adjust_method  = "none",
                                    batch_size     = 1,
                                    n_permutations = 1000,
                                    a              = 1,
                                    seed           = NULL) {

  cl <- match.call()
  if (!is.null(seed)) set.seed(seed)
  if (!is.list(populations) || length(populations) < 2)
    stop("`populations` must be a list with at least 2 groups.")
  .check_populations(populations, binary = TRUE)
  batch_size     <- .check_count(batch_size, "batch_size")
  n_permutations <- .check_count(n_permutations, "n_permutations")
  alpha          <- .check_proportion(alpha, "alpha")
  a              <- .check_positive(a, "a")

  settings <- list(alpha = alpha, method = method,
                   adjust_method = adjust_method, batch_size = batch_size,
                   n_permutations = n_permutations, a = a, seed = seed)

  Npop <- lengths(populations)

  make_key <- function(i, j) paste(i, j, sep = "-")

  freq       <- compute_edge_frequencies(populations)
  edge_pvals <- compute_edge_pvalues(freq$edge_counts, Npop,
                                     method        = method,
                                     adjust_method = adjust_method)
  edge_df    <- rank_edges(edge_pvals)
  n_edges    <- nrow(edge_df)
  if (n_edges == 0L)
    return(.critical_links(NULL, list(), populations, NA_real_, 0L,
                           settings, cl))

  ## Edge-wise decomposition of T (Section 3 of the paper) and the vectorised
  ## permutation null; the helpers live in R/permutation-null.R and are shared
  ## with global_test().
  obs_delta_info <- .observed_edge_deltas(freq$edge_counts, Npop, a)

  key_all   <- make_key(obs_delta_info$indices[, 1], obs_delta_info$indices[, 2])
  map_idx   <- match(make_key(edge_df$node1, edge_df$node2), key_all)
  delta_ord <- obs_delta_info$deltas[map_idx]

  prefix_obs <- cumsum(delta_ord)
  T0         <- sum(obs_delta_info$deltas)

  X           <- .graph_edge_matrix(populations, obs_delta_info$indices)
  C_list      <- .permuted_edge_counts(X, Npop, n_permutations)
  delta_all   <- .permuted_edge_deltas(C_list, Npop, a)
  perm_deltas <- t(delta_all[map_idx, , drop = FALSE])

  ## Summed in the same (upper-triangle) order as in global_test(), so that
  ## the two functions evaluate bit-identical statistics on the same draws.
  T_perm0     <- colSums(delta_all)
  prefix_perm <- t(apply(perm_deltas, 1, cumsum))

  initial_p <- mean(T_perm0 < T0)
  if (initial_p > alpha) {
    warning("Initial test is not significant (p = ",
            round(initial_p, 4),
            "). Populations may be identical or differences too small to detect.")
    return(.critical_links(NULL, list(), populations, initial_p, n_edges,
                           settings, cl))
  }

  batch_steps <- seq(batch_size, n_edges, by = batch_size)
  if (length(batch_steps) == 0L || batch_steps[length(batch_steps)] != n_edges)
    batch_steps <- c(batch_steps, n_edges)

  delta_vec  <- T_perm0 - T0
  R_at_steps <- sweep(prefix_perm[, batch_steps, drop = FALSE],
                      2, prefix_obs[batch_steps])
  p_at_steps <- colMeans(R_at_steps > delta_vec)

  nonsig_idx <- which(p_at_steps > alpha)[1]
  k_removed  <- if (is.na(nonsig_idx)) n_edges else batch_steps[nonsig_idx]

  edges_removed <- vector("list", k_removed)
  for (idx in seq_len(k_removed)) {
    i <- edge_df$node1[idx]; j <- edge_df$node2[idx]
    for (pop in seq_along(populations))
      for (g in seq_len(Npop[pop])) {
        populations[[pop]][[g]][i, j] <- 0
        populations[[pop]][[g]][j, i] <- 0
      }
    edges_removed[[idx]] <- c(i, j)
  }

  critical_edges <- if (k_removed > 0) edge_df[seq_len(k_removed), ] else NULL

  .critical_links(critical_edges, edges_removed, populations, initial_p,
                  n_edges, settings, cl)
}
